apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-sensor
  annotations:
    image.openshift.io/triggers: >
      [{"from":{"kind":"ImageStreamTag","name":"temperature-sensor:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"temperature-sensor\")].image"}]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-sensor
  template:
    metadata:
      labels:
        app: temperature-sensor
    spec:
      containers:
        - name: temperature-sensor
          image: temperature-sensor:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: temperature-sensor
spec:
  selector:
    app: temperature-sensor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
